<?php
/**
 * StationControllerTest.php
 */

namespace App\Http\Controllers;


class StationControllerTest extends \TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate');
    }

    public function tearDown(): void
    {
        $this->artisan('migrate:reset');
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testAllEmpty()
    {
        $response = $this->get('/api/devices');
        $response->assertResponseStatus(200);
        $response->receiveJson([]);
    }

    public function testAll()
    {

    }

    public function testCreate()
    {

    }

    public function testEnter()
    {

    }

    public function testExit()
    {

    }

    public function testFind()
    {

    }

    public function testDriveThrough()
    {

    }
}
